### ISSUE TITLE
(Unknown BlockType:Zero Packet??)

### ISSUE THREAD

**Issue by MohamedSaif44** [ZerBea/hcxdumptool#106]
first i shall say thank you for all your dedication and your consistent effort.
now,after i followed the instruction you mentioned in the guidelines(first_steps),also used and passed every test like:
--check_driver              
--check_injection:also verified by other tool:airplay-ng  and some other tool i can't remember
in in the end i got these results if it can even be called so:
used this:sudo hcxdumptool --silent  -i wlx503eaae72d58 -o dump.pcapng   --enable_status=1 

1.5 hour later:
![Screenshot from 2020-04-02 16-34-15](https://user-images.githubusercontent.com/26437705/78270502-31deda80-750b-11ea-9369-76d115a52282.png)
then this :hcxpcaptool -z test dump.pcapng-0 
![Screenshot from 2020-04-02 18-39-53](https://user-images.githubusercontent.com/26437705/78275161-85ecbd80-7511-11ea-8ba5-1e4c37ff0a42.png)

OS:Ubuntu 18.04
device:tp-link tl-wn722n v3.0
driver:rtl8188eu

**Comment by ZerBea** [comment]
You're dumping to dump.pcapng (hcxdumptool), but you're trying to read dump-pcapng-0 (hcxpcaptool).
hcxdumptool will store captured packets in the file, selected by option "-o". If this file exists, hcxdumptool doesn't overwrite it. Instead it append a sequential number starting with -0
Please comment output of
$ hcxpcapngtool dump-pcapng

Please attach dump.pcapng-0

BTW:
hcxpcaptool is marked as deprecated. Please use hcxpcapngtool.

**Comment by ZerBea** [comment]
Are you running latest git head of hcxtools?
Please comment also output of
$ hcxpcaptool -v

The last version printing that error message "unknown blocktype x after packet x" was 5.1.6!

**Comment by ZerBea** [comment]
Just released hcxtools v6.0.0.
hcxpcaptool <= v5.3.0 is deprecated and will not work in combination with hcxdumptool >= v6.0.0
Please reopen issue, if hcxpcapngtool v6.0.0 is not working on your dumpfile.
