### ISSUE TITLE
confusing check in process_packet()

### ISSUE THREAD

**Issue by hops** [ZerBea/hcxdumptool#108]
I've noticed that in `process_packet()` the `ieee82011len` is checked twice if it's smaller than `MAC_SIZE_ACK`
https://github.com/ZerBea/hcxdumptool/blob/master/hcxdumptool.c#L3916-L3928
This was introduced in commit a09e0cf Before the later check was against `MAC_SIZE_ACK` so I assume this would be the intended way.

**Comment by ZerBea** [comment]
Thanks for reporting that. I forgot to remove old debug code.
Should be fixed by this commit:
https://github.com/ZerBea/hcxdumptool/commit/a75c0f30f34966ebe091fb6a5b25491ec83c4aa7
Cheers
Mike
