### ISSUE TITLE
PMKID Issue (Possibly)

### ISSUE THREAD

**Issue by shakim24** [ZerBea/hcxdumptool#118]
I'm sorta confused with how I can't generate a PMKID. It's been a while since I've used this tool so maybe it has been updated. 

The command I use to generate a hash in hcxdumptool is this: 
./hcxdumptool -o hash -i wlan0mon --filterlist_ap=filter.txt --filtermode=2 --enable_status=1

 my filter.txt file is in the hcxdumptool directory. It takes about maybe 20-30 minutes to generate a result:

/hcxdumptool -o hash -i wlan0mon --filterlist_ap=filter.txt --filtermode=2 --enable_status=1
initialization...
warning: wlan0mon is probably a virtual monitor interface
interface is already in monitor mode

start capturing (stop with ctrl+c)
NMEA 0183 SENTENCE........: N/A
INTERFACE NAME............: wlan0mon
INTERFACE HARDWARE MAC....: c04a0015e205
DRIVER....................: ath9k_htc
DRIVER VERSION............: 5.6.0-kali2-amd64
DRIVER FIRMWARE VERSION...: 1.4
ERRORMAX..................: 100 errors
BPF code blocks...........: 0
FILTERLIST ACCESS POINT...: 1 entries
FILTERLIST CLIENT.........: 0 entries
FILTERMODE................: attack
WEAK CANDIDATE............: 12345678
ESSID list................: 0 entries
ROGUE (ACCESS POINT)......: 00a054166162 (BROADCAST HIDDEN)
ROGUE (ACCESS POINT)......: 00a054006163 (BROADCAST OPEN)
ROGUE (ACCESS POINT)......: 00a054166164 (incremented on every new client)
ROGUE (CLIENT)............: f04f7c78e227
EAPOLTIMEOUT..............: 20000 usec
REPLAYCOUNT...............: 61869
ANONCE....................: d07978c7f65029e827120784bf537ab341a301e547255b00bd878b397ebf73c2
SNONCE....................: 5a5953abdaada490af85f873f2f367caacb96c77b5ef8e8212c58bca0c78f234

21:19:54  11 c0d2ddf37b99 d80f99ae037e (name of network here) [PMKID:92b716905aba40a44cd1589fbe2685ee KDV:2]
^C
terminating...
root@kali:/home/kali/Desktop/hcxdumptool# 

So when I transfer my hash file to hcxtool and run the ./hcxpcaptool  -z pass hash command it doesnt generate a PMKID pass: 

/hcxpcaptool -z pass hash

reading from hash
                                                
summary capture file:                           
---------------------
file name........................: hash
file type........................: pcapng 1.0
file hardware information........: x86_64
capture device vendor information: c04a00
file os information..............: Linux 5.6.0-kali2-amd64
file application information.....: hcxdumptool 6.0.7-3-gf28380b (custom options)
network type.....................: DLT_IEEE802_11_RADIO (127)
endianness.......................: little endian
read errors......................: flawless
minimum time stamp...............: 25.06.2020 00:51:14 (GMT)
maximum time stamp...............: 25.06.2020 02:08:47 (GMT)
packets inside...................: 89
skipped damaged packets..........: 0
packets with GPS NMEA data.......: 0
packets with GPS data (JSON old).: 0
packets with FCS.................: 89
beacons (total)..................: 1
probe requests...................: 39
probe responses..................: 1
EAPOL packets (total)............: 48
EAPOL packets (WPA2).............: 48
PMKIDs (not zeroed - total)......: 1
PMKIDs (WPA2)....................: 5
PMKIDs from access points........: 1
best handshakes (total)..........: 1 (ap-less: 0)
best PMKIDs (total)..............: 1

summary output file(s):
-----------------------
0 PMKID(s) written to pass

root@kali:/home/kali/Desktop/hcxtools# 

Im stumped because it says best PKMID total is 1. I've read a few posts on here where tools were updated as far as ways to generate a PMKID. Can you explain that further. Also, I use  the airmon-ng command to put my adapter in monitor mode. I did that prior to briefly reading your reasoning not to put it in monitor mode that way. Can you touch on that a little as well also, thanks.

**Comment by ZerBea** [comment]
First you should know that not every ACCESS POINT transmit a PMKID. 
Next to know and described in README.md that hcxpcaptool is deprecated. Successor is hcxpcapngtool. That means if you run hcxdumptool >= v6.0.0 you must use hcxpcapngtool >= v6.0.0

```
| deprecated     | obsolete when hashcat and JtR moved to new PMKID/EAPOL hash line - no longer under maintenance                         |
| -------------- | ---------------------------------------------------------------------------------------------------------------------- |
| hcxmactool     | Various MAC based filter operations on HCCAPX and PMKID files - convert hccapx and/or PMKID to new hashline format     |
| hcxpcaptool    | Shows info of pcap/pcapng file and convert it to other hashformats accepted by hashcat and John the Ripper             |
| hcxpmkidtool   | CPU based tools to verfiy a PMKID                                                                                      |
| hcxessidtool   | Various ESSID based filter operations on HCCAPX and PMKID files                                                        |
| hcxhashcattool | Convert old hashcat (<= 5.1.0) separate potfile (2500 and/or 16800) to new potfile format                              |
| wlanwkp2hcx    | Converts wpk (ELMCOMSOFT EWSA projectfile) to hccapx                                                                   |
| wlanhcx2ssid   | Strips BSSID, ESSID, OUI                                                                                               |
| wlanhcxinfo    | Shows detailed info from contents of hccapxfile                                                                        |
| wlanhcxcat     | Simple password recovery tool for WPA/WPA2/WPA2 SHA256 AES-128-CMAC (hash-modes 2500, 2501)                            |
| wlanpmk2hcx    | Converts plainmasterkey and ESSID for use with hashcat hash-mode 12000 or john PBKDF2-HMAC-SHA1                        |
| wlanjohn2hcx   | Converts john wpapsk hashfiles for use with hashcat hash-modes 2500, 2501                                              |
| wlanhcx2john   | Converts hccapx to format expected by John the Ripper                                                                  |
```

Next to know is that you shouldn't use airmon-ng in combination with hcxdumptool. You received a warning:
warning: wlan0mon is probably a virtual monitor interface
interface is already in monitor mode

That is mentioned in --help:
```
hcxdumptool 6.0.7-2-g1c73570  (C) 2020 ZeroBeat
usage  : hcxdumptool <options>
         press the switch to terminate hcxdumptool
         hardware modification is necessary, read more:
         https://github.com/ZerBea/hcxdumptool/tree/master/docs
example: hcxdumptool -o output.pcapng -i wlp39s0f3u4u5 -t 5 --enable_status=3
         do not run hcxdumptool on logical (NETLINK) interfaces (monx, wlanxmon)
         do not use hcxdumptool in combination with 3rd party tools, which take access to the interface (except: tshark, wireshark, tcpdump)
```

Also you should know that, since release of hashcat v6.0.0 hashmode 2500 (hccapx) and 16800 (PMKID) are deprecated:
https://hashcat.net/forum/thread-9303.html
The new hashformat for PMKID and EAPOL is 22000.

So your workflow should be:
```
$ systemctl stop NetworkManager.service
$ systemctl stop wpa_supplicant.service
$ hcxdumptool -o dump.pcapng -i wlan0 --filterlist_ap=filter.txt --filtermode=2 --enable_status=1
$ hcxpcapngtool -o hash.22000 dump.pcapng
$ hashcat -m 22000 hash.22000 wordlist
```
If you really need the old hasmodes (2500 and 16800) they are still implemented in hcxpcapngtool:
```
--pmkid=<file>                     : output deprecated PMKID file (delimter *)
--hccapx=<file>                    : output deprecated hccapx v4 file
--hccap=<file>                     : output deprecated hccap file
--john=<file>                      : output deprecated PMKID/EAPOL (JtR wpapsk-opencl/wpapsk-pmk-opencl)

$ hcxpcapngtool --pmkid=hash.16800 dump.pcapng
$ hcxpcapngtool --hccapx=hash.hccapx dump.pcapng
$ hcxpcapngtool --hccap=hash.hccap dump.pcapng
$ hcxpcapngtool --john=john.hccap dump.pcapng
```

And keep in mind:
Do not(!) use airmon-ng to set monitor mode!

This is not an hcxdumptool issue, so I closed this report - but you can still ask your questions here.
