### ISSUE TITLE
Libressl

### ISSUE THREAD

**Issue by avalonv** [ZerBea/hcxdumptool#128]
Would it be possible to support libressl as an alternative openssl?

**Comment by ZerBea** [comment]
Why?
As long as Arch doesn't replace openSSL with librSSL and nearly every other tool is using openSSL, there is no need for me to support it.
https://bbs.archlinux.org/viewtopic.php?id=180502
https://bbs.archlinux.org/viewtopic.php?id=246756

**Comment by avalonv** [comment]
I think lots of non-arch users want to use this software. Void is a relatively well known distribution that uses libressl, and that prevents us from building hcxdumptool.

**Comment by ZerBea** [comment]
https://github.com/void-linux/void-packages/issues/20935

And I'm not sure that libressl support all HMAC/OMAC functions, used by hcxdumptool/hcxtools.
BTW:
There is a similar request for openWRT:
https://github.com/ZerBea/hcxtools/issues/106

**Comment by avalonv** [comment]
Understandable. I hadn't seen that issue before, I personally don't have a huge preference for either library, but I hope they do switch to OpenSSL if it makes things easier.

**Comment by ZerBea** [comment]
You may have noticed that I haven't closed this request:
https://github.com/ZerBea/hcxtools/issues/106

mbedTLS is really lightweight and I think about it to switch over to this lib - if all functions can be realized with this lib, inclusive Elliptic Curve Diffie-Hellman (ECDH)-​Exchange and Elliptic Curve Digital Signature Algorithm (ECDSA).
