### ISSUE TITLE
gpio options not working

### ISSUE THREAD

**Issue by Czechball** [ZerBea/hcxdumptool#129]
I wired up my led and button as shown in https://github.com/ZerBea/hcxdumptool/blob/master/docs/gpiowait.odg, but when I start hcxdumptool with ``hcxdumptool -i wlan1  --enable_status=19 --gpio_button=4 --gpio_statusled=17``, hcxdumptool instantly terminates after startup. When I omit the --gpio_button option, hcxdumptool works but the connected LED still doesn't light up.

hcxdumptool output:
```
start capturing (stop with ctrl+c)
NMEA 0183 SENTENCE........: N/A
INTERFACE NAME............: wlan1
INTERFACE HARDWARE MAC....: 940c6d896175
DRIVER....................: ath9k_htc
DRIVER VERSION............: 4.19.118-Re4son-v7+
DRIVER FIRMWARE VERSION...: 1.4
ERRORMAX..................: 100 errors
BPF code blocks...........: 0
FILTERLIST ACCESS POINT...: 0 entries
FILTERLIST CLIENT.........: 0 entries
FILTERMODE................: unused
WEAK CANDIDATE............: 12345678
ESSID list................: 0 entries
ROGUE (ACCESS POINT)......: 00bb3ae6be05 (BROADCAST HIDDEN)
ROGUE (ACCESS POINT)......: 00bb3ae6be06 (BROADCAST OPEN)
ROGUE (ACCESS POINT)......: 00bb3ae6be07 (incremented on every new client)
ROGUE (CLIENT)............: b0ece17ff7f7
EAPOLTIMEOUT..............: 20000 usec
REPLAYCOUNT...............: 61448
ANONCE....................: 440ca3a8bada6205a2f6986ad721d5b9e10e0150bf01dd18a3b4540010360380
SNONCE....................: 8073bb4b89c5b2759eb3c444f08ae11a4585363b2ba285808e3c1faba1e66fe4


terminating...
```
My hcxdumptool version is `6.0.7-33-g570cca4`

**Comment by ZerBea** [comment]
Double check you circut. On startup hcxdumptool check the status of the pull down resistors (330 Ohm and 10 KOhm). This resistors are mandatory to ground the line. Otherwise hcxdumptool assume the line is high and terminates.

**Comment by ZerBea** [comment]
What Raspberry Pi model do you use?

**Comment by Czechball** [comment]
Raspberry Pi 3B+

**Comment by Czechball** [comment]
![hcxdumptool circuit](https://user-images.githubusercontent.com/13371865/88419081-d0f24f80-cde4-11ea-93db-4f10a3522958.jpg)
here's a picture of my circuit

**Comment by Czechball** [comment]
nevermind, I'm an idiot. I'll rewire the entire thing

**Comment by ZerBea** [comment]
Let's do another test to make sure the RPI 3 is detected correctly:

Please add a printf() here:
https://github.com/ZerBea/hcxdumptool/blob/master/hcxdumptool.c#L5774
```
gpiobasemem = getrpirev();
printf("\n\ndebug  %08x\n\n", gpiobasemem);
if(gpiobasemem == 0)
```
we expect to see value of GPIO_PERI_BASE_NEW = 0x3F000000

**Comment by ZerBea** [comment]
BTW:
It happened very often to me, that the wires are connected the wrong way. The RPIU doesn't break, because the lines are secured by resistors, but it will not work as expected.
![IMG_20200724_185903](https://user-images.githubusercontent.com/17742243/88421167-59beba80-cde8-11ea-813f-2450bcab9ef4.jpg)

**Comment by Czechball** [comment]
What I did wrong in my photo was that I assumed that the main lines in that breadboard are interconnected vertically, when they're actually connected horizontally...
![73364152_519627458820252_8485226695232585728_n](https://user-images.githubusercontent.com/13371865/88421277-938fc100-cde8-11ea-82e4-685d0231d753.png)

**Comment by ZerBea** [comment]
Correct, I have a similar kind of a board.

**Comment by Czechball** [comment]
Alright, I did the change in hcxdumptool.c and now I get this output
```
kali@kali:~/hcxdumptool$ sudo hcxdumptool -i wlan1 --enable_status=19 --gpio_button=4 gpio_statusled=17
initialization...


debug  3f000000

warning: NetworkManager is running with pid 485
 (possible interfering hcxdumptool)
warning: wpa_supplicant is running with pid 578
 (possible interfering hcxdumptool)

start capturing (stop with ctrl+c)
NMEA 0183 SENTENCE........: N/A
INTERFACE NAME............: wlan1
INTERFACE HARDWARE MAC....: 940c6d896175
DRIVER....................: ath9k_htc
DRIVER VERSION............: 4.19.118-Re4son-v7+
DRIVER FIRMWARE VERSION...: 1.4
ERRORMAX..................: 100 errors
BPF code blocks...........: 0
FILTERLIST ACCESS POINT...: 0 entries
FILTERLIST CLIENT.........: 0 entries
FILTERMODE................: unused
WEAK CANDIDATE............: 12345678
ESSID list................: 0 entries
ROGUE (ACCESS POINT)......: 18421d7f2343 (BROADCAST HIDDEN)
ROGUE (ACCESS POINT)......: 18421d7f2344 (BROADCAST OPEN)
ROGUE (ACCESS POINT)......: 18421d7f2345 (incremented on every new client)
ROGUE (CLIENT)............: b025aa7426ff
EAPOLTIMEOUT..............: 20000 usec
REPLAYCOUNT...............: 64539
ANONCE....................: 287f33bad44643f069753c780c2894586c954fd6cd831bf6dc157a72bf252d90
SNONCE....................: d958f7b67edf7e6567100d5a329f923c571fcf249c1274046c988d069ad3fc1a


terminating...
```

**Comment by Czechball** [comment]
My new circuit looks like this:
![hcxdumptool new circuit - kopie](https://user-images.githubusercontent.com/13371865/88421792-698ace80-cde9-11ea-9a39-e62fa5fb6b5c.jpg)
(red = 3.3v, black = ground, yellow = 7 (gpio 4), orange = 11 (gpio 17)

**Comment by ZerBea** [comment]
Great. The RPI 3 is detected and teh GPIO is initialized as expceted.

warning: NetworkManager is running with pid 485
 (possible interfering hcxdumptool)
warning: wpa_supplicant is running with pid 578
 (possible interfering hcxdumptool)

Both services must be stopped.

But there is still something wrong with the wiring.

Please try without --gpio_button=4 and check if the LED is flashsing.
Also please use --enable_status=95 to get more warnings and status messages.

**Comment by Czechball** [comment]
NetworkManager and wpa_supplicant aren't interfering, I sucesfully used hcxdumptool before with both of these running and no issued occured.
However, I stopped wpa_supplicant service and marked wlan1 as unmanaged in nmcli.

Test without button:
```
kali@kali:~/hcxdumptool$ sudo hcxdumptool -i wlan1 --enable_status=95 gpio_statusled=17
initialization...
warning: NetworkManager is running with pid 485
 (possible interfering hcxdumptool)
warning: wpa_supplicant is running with pid 1613
 (possible interfering hcxdumptool)

start capturing (stop with ctrl+c)
NMEA 0183 SENTENCE........: N/A
INTERFACE NAME............: wlan1
INTERFACE HARDWARE MAC....: 940c6d896175
DRIVER....................: ath9k_htc
DRIVER VERSION............: 4.19.118-Re4son-v7+
DRIVER FIRMWARE VERSION...: 1.4
ERRORMAX..................: 100 errors
BPF code blocks...........: 0
FILTERLIST ACCESS POINT...: 0 entries
FILTERLIST CLIENT.........: 0 entries
FILTERMODE................: unused
WEAK CANDIDATE............: 12345678
ESSID list................: 0 entries
ROGUE (ACCESS POINT)......: 00a0546e6b08 (BROADCAST HIDDEN)
ROGUE (ACCESS POINT)......: 00a0546e6b09 (BROADCAST OPEN)
ROGUE (ACCESS POINT)......: 00a0546e6b0a (incremented on every new client)
ROGUE (CLIENT)............: b025aa186414
EAPOLTIMEOUT..............: 20000 usec
REPLAYCOUNT...............: 63025
ANONCE....................: 2a2883f393fa281c32584b8f848b7652ea6a1fb3a0b2e997c9fce44407cda29d
SNONCE....................: 174aa5c442803c4ff96174aff964d3a0f9ee5eb22e48cf1cef158c694ffc9f0e

... normal hcxdumptool activity
```
LED is NOT blinking.

Test with button:
```
kali@kali:~/hcxdumptool$ sudo hcxdumptool -i wlan1 --enable_status=95 --gpio_button=4 gpio_statusled=17
initialization...


debug  3f000000

warning: NetworkManager is running with pid 485
 (possible interfering hcxdumptool)
warning: wpa_supplicant is running with pid 1613
 (possible interfering hcxdumptool)

start capturing (stop with ctrl+c)
NMEA 0183 SENTENCE........: N/A
INTERFACE NAME............: wlan1
INTERFACE HARDWARE MAC....: 940c6d896175
DRIVER....................: ath9k_htc
DRIVER VERSION............: 4.19.118-Re4son-v7+
DRIVER FIRMWARE VERSION...: 1.4
ERRORMAX..................: 100 errors
BPF code blocks...........: 0
FILTERLIST ACCESS POINT...: 0 entries
FILTERLIST CLIENT.........: 0 entries
FILTERMODE................: unused
WEAK CANDIDATE............: 12345678
ESSID list................: 0 entries
ROGUE (ACCESS POINT)......: 005079411834 (BROADCAST HIDDEN)
ROGUE (ACCESS POINT)......: 005079411835 (BROADCAST OPEN)
ROGUE (ACCESS POINT)......: 005079411836 (incremented on every new client)
ROGUE (CLIENT)............: dc70147d8cd5
EAPOLTIMEOUT..............: 20000 usec
REPLAYCOUNT...............: 62787
ANONCE....................: 3b19d3e8d2a3026fa3255f446b3b4d15bee434eb6f226bb80c7d35983ab8a010
SNONCE....................: 72dc85d8211cda47f9eed6adf8984c08ae93ce868f71920f5e6bc1a053084ede


terminating...
```
ACT LED on Rpi blinks once

**Comment by ZerBea** [comment]
To stop the services, was only a notice. That doesn't affect the GPIO.
Let's double check that the besemamory is ok:
$ xxd -c 4 -g 4 /proc/device-tree/soc/ranges

should show something like this:
00000000: 7e000000 ~...
00000004: 3f000000 ?..
00000008: 02000000 ....
...

where this
3f000000
is the base mamory.

**Comment by ZerBea** [comment]
Please check also the value of the pull down resistors (should be 330 Ohm and 10KOhm).

**Comment by ZerBea** [comment]
Additional you can use wiringpi to verify that the pus butto is really working:
https://raspberrypihq.com/use-a-push-button-with-raspberry-pi-gpio/
http://wiringpi.com/examples/quick2wire-and-wiringpi/install-and-testing/

And you can use the "blink" program to test your LED.

**Comment by Czechball** [comment]
``xxd -c 4 -g 4 /proc/device-tree/soc/ranges`` output:
```
00000000: 7e000000  ~...
00000004: 3f000000  ?...
00000008: 01000000  ....
0000000c: 40000000  @...
00000010: 40000000  @...
00000014: 00001000  ....
```
I checked resistor values with my multimeter and confirmed that they're correct.
While probing the circuit, I noticed that the button was in a wrong rotation so it wasn't working - I had to rotate it 90 degrees clockwise so the pins are actually working... 

After this fix, it seems that the led and button are indeed working correctly. At the end, it turned out that the only problem here was my wiring and not hcxdumptool. Thank you very much for all your help and time.

**Comment by ZerBea** [comment]
No problem. Wiring the circuit is a little bit tricky. After assembling a new system, I always had to double check the circuit. And every time I checked it, I found some wiring issues (due to finger trouble).

**Comment by ZerBea** [comment]
Push button and LED are not hard coded, so you can use every GPIO pin you like.

**Comment by Czechball** [comment]
Yeah, I'm aware of that. I'll see if I can design a case for Rpi3b+ that will also house an RTC and the whole setup will run both Kismet on internal WiFi and hcxdumptool on external.

**Comment by ZerBea** [comment]
Correct. Additional hcxdumptool has a big advantage. Neither kismet, nor aircrack-ng nor Wireshark/tshark provide this:
hcxdumptool request missing packets from the target! So we have no(!) packet loss.
