### ISSUE TITLE
Allow server socket to send messages to 127.0.0.1 without MCAST

### ISSUE THREAD

**Issue by DaniloNC** [ZerBea/hcxdumptool#130]
I am writing a python script to parse the status_messages sent to port 60123 and display some information on an Adafruit miniPiTFT.

![2020-07-29_21-30](https://user-images.githubusercontent.com/405967/88873744-fb784a00-d1e2-11ea-9725-306987a0e6b0.png)

Everything is working if I have wlan0 from my RPi0w connected to the wifi. the problem is when I lose the connection or when I try to start hcxdumptool in server mode without any connectivity.

```
...
server socket failed: Network is unreachable.

terminating...
...
```

Please create an option allowing to send the traffic to the loopback IP or create a configuration allowing to change the IP to something other than the Multicast 224.0.0.255

**Comment by DaniloNC** [comment]
Another way to trigger the problem is trying to use hcxdumptool as client when all interfaces are down (but the one hcxdumptool is using as monitor interface)

```
➜  ~ hcxdumptool --enable_status=256
initialization...
setsockopt() IP_ADD_MEMBERSHIP failed: No such device
waiting for hcxdumptool server...
```

**Comment by ZerBea** [comment]
Please try latest git head (new option --ip)

**Comment by DaniloNC** [comment]
It is working great, thanks!
I will upload the code to the GitHub once I clean-up the code.

**Comment by ZerBea** [comment]
Nice to hear that. Allowing local host seems to be a good idea.
Cheers
Mike
