### ISSUE TITLE
Not get result even after more than half hour

### ISSUE THREAD

**Issue by Beegrekokto** [ZerBea/hcxdumptool#14]
I have "Ralink corp. RT3290 Wireless 802.11n 1T/1R PCIe" adapter which comes with my laptop.
I tried:
hcxdumptool -o test.pcapng -i wlo1mon --filterlist=aashik.txt --filtermode=2 --enable_status=4
And waited about an half hour but still don't get PMKId.

**Comment by ZerBea** [comment]
Pushed an update. Please do a git pull an test it again.
But it's also possible that there are no vulnerable routers in your range.

**Comment by Beegrekokto** [comment]
what are the specs of router those are vulnerable routers. I have been testing my own router.

**Comment by Beegrekokto** [comment]
is 802.11n vulnerable

**Comment by ZerBea** [comment]
Well, 802.11n (a,b,g,ac) is a draft for wireless networking transmission methods (for example data rates),  and 802.11i for security mechanisms (protocols).
If 802.11 is activated on  802.11n, 802.11n is vulnerable.

**Comment by ZerBea** [comment]
Closed, since it isn't an issue.
If you need more information about techniques tactics and procedures, please read this threads (completely) and ask your questions there:
https://hashcat.net/forum/thread-6661-page-33.html
https://hashcat.net/forum/thread-7717.html

**Comment by ashleybroughton** [comment]
@Beegrekokto Make sure you enable monitor mode on the wireless adapter
