### ISSUE TITLE
 How to not capture (exclude) networks from a list? thx

### ISSUE THREAD

**Issue by kocoman1** [ZerBea/hcxdumptool#154]
How to not capture (exclude) networks from a list?

**Comment by ZerBea** [comment]
That depend on your target: APs with assigned CLIENTs, APs only, CLIENTs only
Read more about filter options here:
https://github.com/ZerBea/hcxdumptool/issues/149
and here:
https://github.com/ZerBea/hcxdumptool/issues/146

Closed, becasue it isn't an issue, but you can still ask your questions, here.
