### ISSUE TITLE
Android Operation not supported on transport endpoint

### ISSUE THREAD

**Issue by ghost** [ZerBea/hcxdumptool#192]
I have a ath9k usb interface already in monitor mode created as virtual interface
`iw phy phy1 interface add mon0 type monitor`
I tested airodump-ng 1.6.0 and works without issue but when I run `hcxdumptool -i mon0` on android 11 LOS 18.1 I have this error

```
# ./hcxdumptool -i mon0                                                                                                                                               
initialization of hcxdumptool 6.2.4-21-g0fe3b96...
warning possible interfere: wpa_supplicant is running with pid 5043

failed to detect wlan interface: Operation not supported on transport endpoint
warning: failed to init socket

terminating...
1 driver error encountered
failed to restore old SIOCSIWMODE: No such device
failed to restore old SIOCSIFFLAGS and to bring interface up: No such device
```

```
# iw dev
phy#9
	Interface mon0
		ifindex 57
		wdev 0x900000002
		addr c4:e9:XX:XX:XX:XX
		type monitor
```

I tried also to set selinux in permissive mode but no changes.

**Comment by etmatrix** [comment]
Today I compile the kernel on android and I inserted 

`CONFIG_CFG80211_WEXT=y
`

all errors on ioctls disappear, --check_driver works give me only a warning on "interface already in monitor mode".
Get channel works better before start from 0 now the first channel is 1.
CONFIG_CFG80211_WEXT_EXPORT exist only from kernel 4.xx and I have a 3.18, my device is old.
I removed the parameter --force_interface from my run and works, sorry for my stupid issue.

**Comment by ZerBea** [comment]
No, it isn't a stupid issue. The problem is related to the maintainer of the kernel. If he decide to disable some values, some features will not work (as expected).
BTW:
On "CONFIG_CFG80211_WEXT" hcxdumptool is able to set monitor and you don't need a third party tool to do this.
In that case, the remaining warning "interface already in monitor mode" will disappear.
