### ISSUE TITLE
AWUS036NHA works fine on kali VM but not on Bare Metal

### ISSUE THREAD

**Issue by aurhack** [ZerBea/hcxdumptool#210]
I'm running Kali Linux on bare metal and i'm having an error doing this command :

sudo hcxdumptool -i wlan1 -o dumpfile.pcapng --active_beacon --enable_status=1

After getting some beacons probes, pmkidrogues and that type of things this message prints a lot :

23:04:00 2427/4 driver is busy: failed to transmit internal beacon
23:04:01 2427/4 driver is busy: failed to transmit internal beacon
23:04:01 2427/4 driver is busy: failed to transmit internal beacon
23:04:02 2427/4 driver is busy: failed to transmit internal beacon
23:04:03 2427/4 driver is busy: failed to transmit internal beacon
23:04:03 2427/4 driver is busy: failed to transmit internal beacon
23:04:05 2432/5 driver is busy: failed to transmit internal beacon
23:04:05 2432/5 driver is busy: failed to transmit internal beacon
23:04:06 2432/5 driver is busy: failed to transmit internal beacon
23:04:06 2432/5 driver is busy: failed to transmit internal beacon

when i run dmesg this sentence says this :

device wlan1 entered promiscuous mode
[ 1523.275065] ath: phy3: Unable to remove monitor interface at idx: 0
[ 1525.291232] ath: phy3: Unable to remove station entry for monitor mode
[ 1542.884096] usb 1-8: USB disconnect, device number 8
[ 1543.181747] device wlan1 left promiscuous mode

Kali Linux on Virtual Machine works good but this happens on bare metal you know why?

I'm running an AWUS036NHA to this.

**Comment by ZerBea** [comment]
AWUS036NHA device 
https://deviwiki.com/wiki/ALFA_Network_AWUS036NHA
is using an ath9k driver 
https://wireless.wiki.kernel.org/en/users/Drivers/ath9k_htc
And it looks like we have a problem on that driver.

I'll close this issue, because it is related to this one:
https://github.com/ZerBea/hcxdumptool/issues/209
Please follow that report and add your comments there.
