### ISSUE TITLE
What Wireless Adapter should i cop in 2022?

### ISSUE THREAD

**Issue by aurhack** [ZerBea/hcxdumptool#211]
I saw that some drivers are broken, some chipsets doesn't work well, i'm confused and i want to know what Wireless Adapter should i buy that supports Monitor Mode and Packet Injection?

That i can buy on Amazon/

What is the best one you consider that you know it will work as expected on Wifi Hacking?

**Comment by ZerBea** [comment]
As of today all adapters running MediaTek (MT) or Ralink (RT)  chipsets. Both drivers (mt76 and rt2800usb)  support full monitor mode and full packet injection. They are well maintained and part of the Linux stock kernel (not third party driver required):
```
* ID 148f:7601 Ralink Technology, Corp. MT7601U Wireless Adapter
* ID 148f:761a Ralink Technology, Corp. MT7610U ("Archer T2U" 2.4G+5G WLAN Adapter
* ID 0e8d:7612 MediaTek Inc. MT7612U 802.11a/b/g/n/ac Wireless Adapter
* ID 0b05:17d1 ASUSTek Computer, Inc. AC51 802.11a/b/g/n/ac Wireless Adapter [Mediatek MT7610U]
* ID 7392:7710 Edimax Technology Co., Ltd Edimax Wi-Fi
* ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter
* ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter
* ID 148f:5572 Ralink Technology, Corp. RT5572 Wireless Adapter
```

e.g.:
ALFA AWUS036ACM -> MediaTek MT7612U
PANDA PAU06 -> Ralink RT5372

**Comment by aurhack** [comment]
So, from those, what's the one you think works very well and it's your preferible adapter to let me cop one of those? :)

**Comment by ZerBea** [comment]
This are my favorite ones regarding 2.4 and 5 GHz and external antenna connector:
ALFA AWUS036ACM -> MediaTek MT7612U
PANDA PAU06 -> Ralink RT5372

**Comment by aurhack** [comment]
I copped the ACM one, 6th April is coming to my house, let's gooo

**Comment by ZerBea** [comment]
Some information about ALFA AWUS036ACM:
Hardware:
```
$ lsusb
Bus 003 Device 004: ID 0e8d:7612 MediaTek Inc. MT7612U 802.11a/b/g/n/ac Wireless Adapter
```
System configuration:
```
$ uname -r
5.17.1-arch1-1

$ iw reg get
global
country IN: DFS-UNSET
	(2402 - 2482 @ 40), (N/A, 20), (N/A)
	(5150 - 5250 @ 80), (N/A, 30), (N/A)
	(5250 - 5350 @ 80), (N/A, 24), (N/A)
	(5470 - 5725 @ 160), (N/A, 24), (N/A)
	(5725 - 5875 @ 80), (N/A, 30), (N/A)
```
Driver:
```
$ hcxdumptool -I
wlan interfaces:
phy1	00c0cacd1f20	wlp5s0f4u2	(driver:mt76x2u)
```
Supported frequencies and  channels:
```
$ sudo hcxdumptool -i wlp5s0f4u2 -C
initialization of hcxdumptool 6.2.5-60-gd42d16d (depending on the capabilities of the device, this may take some time)...
wlp5s0f4u2 available frequencies, channels and tx power reported by driver:
2412MHz   1 (20 dBm)
2417MHz   2 (20 dBm)
2422MHz   3 (20 dBm)
2427MHz   4 (20 dBm)
2432MHz   5 (20 dBm)
2437MHz   6 (20 dBm)
2442MHz   7 (20 dBm)
2447MHz   8 (20 dBm)
2452MHz   9 (20 dBm)
2457MHz  10 (20 dBm)
2462MHz  11 (20 dBm)
2467MHz  12 (20 dBm)
2472MHz  13 (20 dBm)
2484MHz  14 (20 dBm)
5180MHz  36 (20 dBm)
5200MHz  40 (20 dBm)
5220MHz  44 (20 dBm)
5240MHz  48 (20 dBm)
5260MHz  52 (20 dBm)
5280MHz  56 (20 dBm)
5300MHz  60 (20 dBm)
5320MHz  64 (20 dBm)
5500MHz 100 (20 dBm)
5520MHz 104 (20 dBm)
5540MHz 108 (20 dBm)
5560MHz 112 (20 dBm)
5580MHz 116 (20 dBm)
5600MHz 120 (20 dBm)
5620MHz 124 (20 dBm)
5640MHz 128 (20 dBm)
5660MHz 132 (20 dBm)
5680MHz 136 (20 dBm)
5700MHz 140 (20 dBm)
5720MHz 144 (20 dBm)
5745MHz 149 (20 dBm)
5765MHz 153 (20 dBm)
5785MHz 157 (20 dBm)
5805MHz 161 (20 dBm)
5825MHz 165 (20 dBm)
5845MHz 169 (20 dBm)
5865MHz 173 (20 dBm)

terminating...
```
Driver test:
```
$ sudo hcxdumptool -i wlp5s0f4u2 --check_driver
initialization of hcxdumptool 6.2.5-60-gd42d16d (depending on the capabilities of the device, this may take some time)...
starting driver test...
driver tests passed...
all required ioctl() system calls are supported by driver

terminating...
```
Injection test using supplied antennas:
```
$ sudo hcxdumptool -i wlp5s0f4u2 --check_injection
initialization of hcxdumptool 6.2.5-60-gd42d16d (depending on the capabilities of the device, this may take some time)...
starting antenna test and packet injection test (that can take up to two minutes)...
stage 2 of 2 probing frequency 5865/173 proberesponse 349   
packet injection is working on 2.4GHz!
packet injection is working on 5GHz!
injection ratio: 55% (BEACON: 634 PROBERESPONSE: 349)
your injection ratio is good
antenna ratio: 63% (NETWORK: 19 PROBERESPONSE: 12)
your antenna ratio is good

terminating...
```

Closed with this information, but you can still ask your questions here.

**Comment by aurhack** [comment]
Hey i got the adapter all good but when i do the command : 
sudo hcxdumptool --check_injection -i wlan1

 i gon't get the good antenna ratio u got i get

your antenna radio is poor, is weird..

**Comment by aurhack** [comment]
How i can setup well the adapter? i installed the driver, anyways can you guide me to how to setup it correctly? ( if i'm missing something)

**Comment by ZerBea** [comment]
There is no need to install a driver, because mt76 is build in the Linux kernel. You should run latest stable (5.16 or 5.17) or latest longterm (5.15, but 5.10 is ok, too.
crda and wireless-regdb should be installed and configured - otherwise injection on channel 12,13,14 and 5GHz is not allowed by kernel regulatory:
$ sudo iw req set IN

Network services should be stopped before running hcxdumptool:
$ sudo systemctl stop NetworkManager.service
$ sudo systemctl stop wpa_supplicant.service

If hcxdumptool finished, you have to start them - otherwise you have no connectivity:
$ sudo systemctl start NetworkManager.service
$ sudo systemctl start wpa_supplicant.service

Injection ratio and antenna ratio depend on the responding ACCESS POINTs within range. Less APs in range will result in poor injection ratio and poor antenna ratio.
$ sudo hcxdumptool -i your_interface_name --do_rcascan will give you an overview how many APs are in range and respond to your requests.

**Comment by aurhack** [comment]
I thought it was sizing the potential of the adapter but as you say, it is because the APs are further than i think so, well 5GHz is better on terms of fast browse but on mid range, not fully like 2.4GHz

Anyways i installed a driver of the MT7612U, it will conflict onto anything? If it does, how i can uninstall the driver or something i installed? Maybe that's why it's working weird!

I tested it on Wifite and works well, works as expected but if it will conflict on the adapter, how i can revert it? thanks :)
