### ISSUE TITLE
Frame tool

### ISSUE THREAD

**Issue by Ridda2477** [ZerBea/hcxdumptool#213]
$ ./hcxdumptool -o test.pcapng -i wlp39s0f3u4u5 –enable_status

**Comment by ZerBea** [comment]
Closed due to to less information: What exactly is the issue?
BTW: The command line is missing a status value:
$ hcxdumptool -o test.pcapng -i wlp39s0f3u4u5 --enable_status=95

**Comment by ZerBea** [comment]
Mandatory information is description of the issue and  complete output of:
$ uname -r
$ hcxdumptool -I
$ hcxdumptool -i wlp39s0f3u4u5 --check_driver
$ hcxdumptool -i wlp39s0f3u4u5 --check_injection

Without this information, for me it looks like you typed a wrong command line.
