### ISSUE TITLE
Directory error while using thge command 'make' 

### ISSUE THREAD

**Issue by DakiBhai007** [ZerBea/hcxdumptool#218]
Hello there, 
Used your tool a while ago. Was having certain problems while executing the command 'make' .
The error is given below:

make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
cc -O3 -Wall -Wextra -std=gnu99   -MMD -MF .deps/hcxdumptool.d -o hcxdumptool hcxdumptool.c   -DVERSION_TAG=\"6.2.6-6-ga3fcc5c\" -DVERSION_YEAR=\"2022\"
hcxdumptool.c:42:10: fatal error: openssl/conf.h: No such file or directory
   42 | #include <openssl/conf.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:74: hcxdumptool] Error 1

Hope you provide a solution to me for this.
Thanks!

**Comment by ZerBea** [comment]
It is mandatory to install the dependencies, before running make.
From README.md:
```
Solve dependencies (Debian based distributions: KALI, UBUNTU, ...) 
You need to install missing dependencies before running `make`:
sudo apt-get install libcurl4-openssl-dev libssl-dev pkg-config
```

Closed, because it is not an issue, but you still can ask your questions here.
