### ISSUE TITLE
Filter for reliable handshakes (correct PSK)

### ISSUE THREAD

**Issue by RaduNico** [ZerBea/hcxdumptool#222]
When running hcxdumptool it is possible to capture invalid authentication attempts in the form of M1M2 EAPOL messages, but this authentication attempt might not use the correct PSK.

My questions are the following:
1) what options should I use in order to capture reliable handshakes (which use the correct pre-shared key)? I assume the presence of M3 or obtaining the PMKID can be be considered reliable, but I am not sure how to filter for those situations.

Filtering the handshakes/PMKID with hcxpcapngtool would obviously work as well.

2) Other than M1+M2, are there any other situations where the correct PSK might differ from the one present in the capture?

I tried looking in both repositories for a similar question, if this has been asked before, I am sorry for the overhead. You can close this issue, as it is only a question

**Comment by RaduNico** [comment]
I noticed the explanation for the bitmask but i did not realize that the pair field is the last two characters from the 22000 format. I didn't actually think the 22000 format contained any information about the message pair which generated it. Knowing this, the help page for hcxpcapngtool makes way more sense.

hcxhashtool is exactly what I was looking for. This completely answers my questions, thank you for your time!

**Comment by ZerBea** [comment]
No problem, you're welcome.

Running more than one HASH with the same ESSID is not a big problem for hashcat, due to reuse of PBKDF2. hashcat pay the price (PBKDF2 -> PMK) once. Than thisPMK is comparded to all hashes using the same ESSID.
hashcat will show this in Digests (total hashes) and Salts (hashes with the same ESSID in "Recovered.Total" status line.


BTW:
hcxeiutool does similar on word lists (-E -I -U output of hcxpcapngtool). This lists can be used in combination with masks and/or rules and will give good word lists tailored to the hash list (-o output of hcxpcapngtool).

**Comment by LLH-l** [comment]
Only client handshakes connected to the AP are captured, and other broadcasts not connected to the client are ignored. This capture method is reliable handshakes

**Comment by abidmaria** [comment]
> Only client handshakes connected to the AP are captured, and other broadcasts not connected to the client are ignored. This capture method is reliable handshakes

Hello 
I got this error by executing hcxtool , can you please help 

zsh: segmentation fault sudo hcxdumptool -i wlan0 -o output.pcapng --enable_status=15

Thanks

**Comment by LLH-l** [comment]
> 

Everything is OK in Kali

hcxdumptool -i wlan0 -o kali.pcapng --active_beacon --enable_status=15

**Comment by abidmaria** [comment]
> > 
> 
> Everything is OK in Kali
> 
> hcxdumptool -i wlan0 -o kali.pcapng --active_beacon --enable_status=15

Thank you buy why I  getting this error ? Any advice ?

**Comment by ZerBea** [comment]
I can't reproduce the segmentation fault, too, but I have an idea. It may related to the combination zsh & sudo.
Which version of sudo and zsh do you use?
