### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by kimocoder** [ZerBea/hcxdumptool#225]
Hi brothers, we now have problems with all adapters in Android for some reason it will not work anymore.

Tried a lot of adapters, but all failing for some reason with later releases/commits of hcxdumptool, even kmown supported adapters with all nescessary/provided settings for hcxdumptool.

Instead of sending an email, I opened this thread for anyone to participate in it 🥇

**Comment by RealEnder** [comment]
Hi Chris, do you have a working commit?

**Comment by kimocoder** [comment]
hold on, I will provide more information and logs after dinner 💯

**Comment by kimocoder** [comment]
![Screenshot_20220723-181556_NetHunter Terminal](https://user-images.githubusercontent.com/4252297/180613556-94ffa138-adc0-458f-8c46-c94cd528c5cf.png)

**Comment by kimocoder** [comment]
The issue above is shown is all adapters I try now, different phones, kernels, OOS, LOS, A11, A12. Anywhere.

**Comment by kimocoder** [comment]
![IMG_20220723_181951_962](https://user-images.githubusercontent.com/4252297/180613682-f5c34de5-9b87-49f8-8064-e111325fc56e.jpg)

![IMG_20220723_182012_651](https://user-images.githubusercontent.com/4252297/180613691-c5c88a4a-6394-46fd-bda4-89fb12102100.jpg)

**Comment by kimocoder** [comment]
Above is 6 months back, even doing on a VIF adapter which I know I should not be doing. Same driver "rtl
2800usb"

**Comment by kimocoder** [comment]
If you need me to do some tests or anything debug, just let me know what I can do, because I'm doing better integration of hcx tools in wifite2 these days, and we really need this working 🥇

**Comment by ZerBea** [comment]
Ok, let's hunt for the problem.
Main change was adding active monitor mode in transmit branch which is working as expected on Linux systems.
I'll add some more information to opensocket() to find out what exactly went wrong.

**Comment by kimocoder** [comment]
Awesome. Im available with anything for testing purposes, just let me know what to do or provide 👍

**Comment by ZerBea** [comment]
I think I got it. It is located in opensocket
here:
```
#ifdef PACKET_IGNORE_OUTGOING
if(setsockopt(fd_socket, SOL_PACKET, PACKET_IGNORE_OUTGOING, &enable, sizeof(int)) < 0) return false;
#endif
```

or here:
```
if(set_channel_test(2462) == false) return false;
if(set_channel_test(2412) == false) return false;
```

Pushed an update to identify the problem exactly. Please test latest git head.

**Comment by kimocoder** [comment]
hold on, tests coming up 👍

**Comment by ZerBea** [comment]
Ok, stand by.

**Comment by kimocoder** [comment]
![Screenshot_20220723-192938_Termux](https://user-images.githubusercontent.com/4252297/180616267-aa75fe54-1f93-47dd-9814-784adc2d942f.png)

**Comment by kimocoder** [comment]
We're back in business sir 🥇 
Thanks for participating 🥇

**Comment by ZerBea** [comment]
No problem, you're always welcome.

The price tag on the latest changes is huge:

Active monitor produce 7 times more traffic in case of a crappy connection (target far away).
Ignoring outgoing packets by hcxdumptool increase CPU cycles.

But it still works fine on small devices.
Some commits before I set the time out to 5 seconds - that should be more than enough.

**Comment by kimocoder** [comment]
![Screenshot_20220723-193958_Termux](https://user-images.githubusercontent.com/4252297/180616629-0c838af1-23a2-4fc5-a374-65c80b13c924.png)


Confirmation in tool 👍  Open source community will always be the best

**Comment by ZerBea** [comment]
BTW:
I wonder about Android.
They define PACKET_IGNORE_OUTGOING
but the Protocol is not available.

**Comment by kimocoder** [comment]
I can look for the string tonight 👍  I'll notify you

**Comment by ZerBea** [comment]
BTW:
hcxlabgetmallpr is the evil little sister of hcxdumptool.

**Comment by kimocoder** [comment]
I will investigate the usages.
Right now, my plan is to get rid of airmon-ng usage in wifite2, using a VIF interface will cause interferrance with adapter and rather use 'ip' and 'iw' and better integration/usage of hcx tools

**Comment by kimocoder** [comment]
So, it looks like PACKET_IGNORE_OUTGOING was added in kernel v4.20. Most Android devices at this point haven't even got to kernel v4.20. Latest devices have, but majority not.


add PACKET_IGNORE_OUTGOING sockopt from linux v4.20

new in linux commit fa788d986a3aac5069378ed04697bd06f83d3488

**Comment by kimocoder** [comment]
Correction, it was added in kernel v4.19-rc2 but the same problem, majority of devices isn't on kernel v4.19 at this point too.

**Comment by RealEnder** [comment]
@ZerBea , this can go as compile-time option of hcxdumptool with 4.20+ default.
@kimocoder You can use hcxdumptool to set monitor mode directly on the interface. There is a simple CPU cracker in hcxtools, but in their current version can't read wordlist from file. john may be better alternative, from aircrack-ng/pyrit for sure. wifite2 uses some other old tools, which can be also stripped - it will be easier to maintain with less dependencies.

**Comment by kimocoder** [comment]
Yes, I need to find some replacements soon, crackers used isn't really maintained anymore, that includes John. hashcat is the one which is active maintained at this point, and aircrack-ng of cource. But dont really know about replacement tools atm, we'll see. but moving away from VIF interfaces would be a good start.

**Comment by ZerBea** [comment]
By latest commit, we test for kernel >= 4.20 as compile option. Thanks @RealEnder 
I thought it was enough to test if PACKET_IGNORE_OUTGOING is defined:
https://github.com/ZerBea/hcxdumptool/issues/212
Obviously that wasn't enough.
More information is here:
https://thomasw.dev/post/packet_ignore_outgoing/

@kimocoder JtR (single) and hashcat (a9) have a nice new mode if the PSK is calculated from BSSID or ESSID. That is working like a charm and can be added to wifite2 in an easy way.

**Comment by RealEnder** [comment]
JtR is maintained and functionality added constantly: https://github.com/openwall/john
If compilation is made on the phone (maybe this is the case more often) it will work, but if using crossbuild environment kernel version may be different.

**Comment by ZerBea** [comment]
Just for information:
https://source.android.com/devices/architecture/kernel/android-common

**Comment by kimocoder** [comment]
I'm pulling AKC (common) and CAF (CodeLinaro) to my kernels, vendors certainly never touch it sfter release 🥇  will look at the crackers soon, but the handling of monitor mode is a priority

**Comment by ZerBea** [comment]
For sure, monitor mode and packet injection is high priority.
Unfortunately the airmon-ng way is not the best choice due to iw (and libnl) dependency and the reason why I added to set monitor mode to hcxdumptool/hcxlabtool series.
https://github.com/aircrack-ng/aircrack-ng/issues/1965

**Comment by ZerBea** [comment]
BTW:
Just received this issue report:
https://github.com/ZerBea/hcxtools/issues/218
A good reason to run hcxdumptool instead of a stupid DEAUTHENTICATOR.

**Comment by kimocoder** [comment]
Possible to tag a new release and push soon? We want changes to Kali :1st_place_medal:

**Comment by ZerBea** [comment]
Done: -> 6.2.7
https://github.com/ZerBea/hcxdumptool/releases

and flagged out
https://archlinux.org/packages/community/x86_64/hcxdumptool/
