### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by Taschenmulch** [ZerBea/hcxdumptool#237]
https://github.com/ZerBea/hcxdumptool/blob/bf1b61ee4612baba5aa5c9c788e4dcff7ea6d4e5/hcxdumptool.c#L7089

**Comment by ZerBea** [comment]
Thanks. Fixed by this commit:
https://github.com/ZerBea/hcxdumptool/commit/362a817c835f861c69d04a0d8b7f57ddd6df9db2
