### ISSUE TITLE
known beacons attack

### ISSUE THREAD

**Issue by s0i37** [ZerBea/hcxdumptool#241]
Hi.
I make the known beacons attacks like this:

`sudo hcxdumptool -i mon0 --enable_status=6 --essidlist=essids.txt`

However, hcxdumptool only announce  `WPA` network. Known beacons attack more interesting whith `OPN` networks

**Comment by ZerBea** [comment]
No. Target is only WPA 1, WPA 2 and WPA 2 keyversion 3

BTW;
When running --essidlist=essids.txt, you should use --active_beacon in combination

**Comment by ZerBea** [comment]
You can set BEACON params to what ever you want:
`--beaconparams=<TLVs>              : update or add Information Elements in all reactive and essidlist beacons
`

BTW:
This is more a discussion than an issue report. Closed it here and opened discussion

**Comment by s0i37** [comment]
`When running --essidlist=essids.txt, you should use --active_beacon in combination`
Not necessary.
I want only sends beacons from my dictionary, not previosly seen networks.

**Comment by ZerBea** [comment]
Ok.
