### ISSUE TITLE
ERROR: rtl8821au (this driver is not recommended - expect driver errors)

### ISSUE THREAD

**Issue by nbctcp** [ZerBea/hcxdumptool#250]
ERROR: rtl8821au (this driver is not recommended - expect driver errors)
HW INFO: TP-LINK Archer T2U Plus AC600
SW INFO:
-driver installed https://github.com/morrownr/8821au-20210708.git
-
`# lsusb          
Bus 001 Device 002: ID 2357:0120 TP-Link Archer T2U PLUS [RTL8821AU]
# aireplay-ng --test wlan0  
20:43:05  Trying broadcast probe requests...
20:43:06  Injection is working!
20:43:07  Found 1 AP

# hcxdumptool -o id.pcap -i wlan0 --enable_status=1 --filterlist_ap=id.txt --filtermode=2
This is a penetration testing tool!
It is made to detect vulnerabilities in your NETWORK mercilessly!
Don't report bugs if this tool does exactly what it was coded to do!
initialization of hcxdumptool 6.2.7-59-g0a12c7b (depending on the capabilities of the device, this may take some time)...
BPF is unset. Make sure hcxdumptool is running in a 100% controlled environment!
interface is already in monitor mode, skipping ioctl(SIOCSIWMODE) and ioctl(SIOCSIFFLAGS) system calls
start capturing (stop with ctrl+c)
NMEA 0183 PROTOCOL........: N/A
PHYSICAL INTERFACE........: phy0
INTERFACE NAME............: wlan0
INTERFACE PROTOCOL........: IEEE 802.11b
INTERFACE TX POWER........: 0 dBm (lowest value reported by the device)
INTERFACE HARDWARE MAC....: 2887baafaa2a (not used for the attack)
INTERFACE VIRTUAL MAC.....: 2887baafaa2a (not used for the attack)
DRIVER....................: rtl8821au (this driver is not recommended - expect driver errors)
DRIVER VERSION............: v5.12.5.2-0-g70054197b.20210708
DRIVER FIRMWARE VERSION...: 42.4
openSSL version...........: 1.0
ERRORMAX..................: 100 errors
BPF code blocks...........: 0
FILTERLIST ACCESS POINT...: 1 entries
FILTERLIST CLIENT.........: 0 entries
FILTERMODE................: attack
WEAK CANDIDATE............: 12345678
ESSID list................: 0 entries
ACCESS POINT (ROGUE)......: 000dc25cb63e (BROADCAST WILDCARD used for the attack)
ACCESS POINT (ROGUE)......: 000dc25cb63f (BROADCAST OPEN used for the attack)
ACCESS POINT (ROGUE)......: 000dc25cb640 (used for the attack and incremented on every new client)
CLIENT (ROGUE)............: e00db9b3da0a
EAPOLTIMEOUT..............: 20000 usec
EAPOLEAPTIMEOUT...........: 2500000 usec
REPLAYCOUNT...............: 62955
ANONCE....................: ce3e2bfb7d0d9400431210a2358e9a6231a7ef8ca5d274c1fc8fde0cecb8f772
SNONCE....................: d3bdceb082e45a86aa580b7f3ba45de9a0dba3ec1a3b5237530d32149a889aa8
TIME     FREQ/CH  MAC_DEST     MAC_SOURCE   ESSID [FRAME TYPE]`

?
1. could you tell me which driver should I use
tq

**Comment by ZerBea** [comment]
hcxdumptool use WIRELESS EXTENSIONS to control the device. Unfortunately some Realtek drivers do not support this calls. They use NETLINK instead and dropped WIRELESS EXTENSIONS. All(!) rtl88xxau drivers are based on NETLINK only.

aircrack-ng suite, iw and ip use libnl to communicate via NETLINK (nl80211) to control the device. That is absolutely no option for me:
airmon-ng -> iw -> libnl (nl80211) -> driver
airodump-ng -> libnl -> (nl80211) -> driver
but
hcxdumptool -> WIRELESS EXTENSIONS -> driver

Currently I'm working on a new version that use nl80211 without running into the dependency of libnl:
hcxdumptool -> WIRELESS EXTENSIONS/NETLINK -> driver
```
$ ./hcxlabtool -I -C

available wlan devices:

phy idx hw-mac       virtual-mac  m ifname           driver (protocol)
---------------------------------------------------------------------------------------------
  0   3 aca213117f56 aca213117f56 + wlp39s0f3u1u2    mt7601u (WIRELESS EXTENSIONS & NETLINK)
  1   4 3c7c3f498de0 3c7c3f498de0 + wlp39s0f3u1u3    mt76x0u (WIRELESS EXTENSIONS & NETLINK)
  3   7 f81a670dc527 f81a670dc527 + wlp39s0f3u1u1u2  rtl8xxxu (WIRELESS EXTENSIONS & NETLINK)
  6   9 74da380645e7 74da380645e7 + wlp39s0f3u1u4    rtl88XXau (NETLINK)
  7  10 7cdd908965fb 7cdd908965fb + wlp39s0f3u1u1u3  rt2800usb (WIRELESS EXTENSIONS & NETLINK)

+ monitor mode available
- no monitor mode available


wlp39s0f3u1u2 default scan list: frequency [channel] tx-power
  2412 [1] 20.0 dBm	  2417 [2] 20.0 dBm	  2422 [3] 20.0 dBm	  2427 [4] 20.0 dBm
  2432 [5] 20.0 dBm	  2437 [6] 20.0 dBm	  2442 [7] 20.0 dBm	  2447 [8] 20.0 dBm
  2452 [9] 20.0 dBm	  2457 [10] 20.0 dBm	  2462 [11] 20.0 dBm	  2467 [12] 20.0 dBm
  2472 [13] 20.0 dBm

wlp39s0f3u1u3 default scan list: frequency [channel] tx-power
  2412 [1] 16.0 dBm	  2417 [2] 16.0 dBm	  2422 [3] 16.0 dBm	  2427 [4] 16.0 dBm
  2432 [5] 16.0 dBm	  2437 [6] 16.0 dBm	  2442 [7] 16.0 dBm	  2447 [8] 16.0 dBm
  2452 [9] 16.0 dBm	  2457 [10] 16.0 dBm	  2462 [11] 16.0 dBm	  2467 [12] 16.0 dBm
  2472 [13] 16.0 dBm	  5180 [36] 20.0 dBm	  5200 [40] 20.0 dBm	  5220 [44] 20.0 dBm
  5240 [48] 20.0 dBm	  5260 [52] 20.0 dBm	  5280 [56] 20.0 dBm	  5300 [60] 20.0 dBm
  5320 [64] 20.0 dBm	  5500 [100] 20.0 dBm	  5520 [104] 20.0 dBm	  5540 [108] 20.0 dBm
  5560 [112] 20.0 dBm	  5580 [116] 20.0 dBm	  5600 [120] 20.0 dBm	  5620 [124] 20.0 dBm
  5640 [128] 20.0 dBm	  5660 [132] 20.0 dBm	  5680 [136] 20.0 dBm	  5700 [140] 20.0 dBm
  5720 [144] 13.0 dBm	  5745 [149] 13.0 dBm	  5765 [153] 13.0 dBm	  5785 [157] 13.0 dBm
  5805 [161] 13.0 dBm	  5825 [165] 13.0 dBm	  5845 [169] 13.0 dBm	  5865 [173] 13.0 dBm


wlp39s0f3u1u1u2 default scan list: frequency [channel] tx-power
  2412 [1] 20.0 dBm	  2417 [2] 20.0 dBm	  2422 [3] 20.0 dBm	  2427 [4] 20.0 dBm
  2432 [5] 20.0 dBm	  2437 [6] 20.0 dBm	  2442 [7] 20.0 dBm	  2447 [8] 20.0 dBm
  2452 [9] 20.0 dBm	  2457 [10] 20.0 dBm	  2462 [11] 20.0 dBm	  2467 [12] 20.0 dBm
  2472 [13] 20.0 dBm

wlp39s0f3u1u4 default scan list: frequency [channel] tx-power
  2412 [1] 20.0 dBm	  2417 [2] 20.0 dBm	  2422 [3] 20.0 dBm	  2427 [4] 20.0 dBm
  2432 [5] 20.0 dBm	  2437 [6] 20.0 dBm	  2442 [7] 20.0 dBm	  2447 [8] 20.0 dBm
  2452 [9] 20.0 dBm	  2457 [10] 20.0 dBm	  2462 [11] 20.0 dBm	  2467 [12] 20.0 dBm
  2472 [13] 20.0 dBm	  2484 [14] 20.0 dBm	  5075 [15] 30.0 dBm	  5080 [16] 30.0 dBm
  5085 [17] 30.0 dBm	  5090 [18] 30.0 dBm	  5100 [20] 30.0 dBm	  5120 [24] 30.0 dBm
  5140 [28] 30.0 dBm	  5160 [32] 23.0 dBm	  5180 [36] 23.0 dBm	  5200 [40] 23.0 dBm
  5220 [44] 23.0 dBm	  5240 [48] 23.0 dBm	  5260 [52] 20.0 dBm	  5280 [56] 20.0 dBm
  5300 [60] 20.0 dBm	  5320 [64] 20.0 dBm	  5340 [68] 20.0 dBm	  5360 [72] 30.0 dBm
  5380 [76] 30.0 dBm	  5400 [80] 30.0 dBm	  5420 [84] 30.0 dBm	  5440 [88] 30.0 dBm
  5460 [92] 30.0 dBm	  5480 [96] 26.0 dBm	  5500 [100] 26.0 dBm	  5520 [104] 26.0 dBm
  5540 [108] 26.0 dBm	  5560 [112] 26.0 dBm	  5580 [116] 26.0 dBm	  5600 [120] 26.0 dBm
  5620 [124] 26.0 dBm	  5640 [128] 26.0 dBm	  5660 [132] 26.0 dBm	  5680 [136] 26.0 dBm
  5700 [140] 26.0 dBm	  5720 [144] 13.0 dBm	  5745 [149] 13.0 dBm	  5765 [153] 13.0 dBm
  5785 [157] 13.0 dBm	  5805 [161] 13.0 dBm	  5825 [165] 13.0 dBm	  5845 [169] 13.0 dBm
  5865 [173] 13.0 dBm	  5885 [177] 30.0 dBm

wlp39s0f3u1u1u3 default scan list: frequency [channel] tx-power
  2412 [1] 20.0 dBm	  2417 [2] 20.0 dBm	  2422 [3] 20.0 dBm	  2427 [4] 20.0 dBm
  2432 [5] 20.0 dBm	  2437 [6] 20.0 dBm	  2442 [7] 20.0 dBm	  2447 [8] 20.0 dBm
  2452 [9] 20.0 dBm	  2457 [10] 20.0 dBm	  2462 [11] 20.0 dBm	  2467 [12] 20.0 dBm
  2472 [13] 20.0 dBm

bye-bye
```
The tested Realtek driver is from here:
rtl88XXau (as you can see NETLINK only)
https://github.com/aircrack-ng/rtl8812au

and here:
rtl8xxxu (luckily support of WIRELESS EXTENSIONS and NETLINK)
https://github.com/kimocoder/realtek_rtwifi

If the basic functions are coded and tested, I'll push them to:
https://github.com/ZerBea/wifi_laboratory

I think we can close this here, because there is no (known) WIRELESS EXTENSION driver for this interface.
