### ISSUE TITLE
Search for infinite networks and mac address of the unattached filter

### ISSUE THREAD

**Issue by linuxiano85** [ZerBea/hcxdumptool#31]
For days I try to crack my wifi and create the file filter.txt and even if it finds the corresponding network does not perform any attack. After many hours it is still in scan.

**Comment by ZerBea** [comment]
Nearly all issues are related to the distribution (for example KALI, the configuration of the distribution and the driver).
Please read this:
https://hashcat.net/forum/thread-7717-post-41797.html#pid41797

**Comment by ZerBea** [comment]
Pushed an update to get rid of this issues.
Please read this:
https://hashcat.net/forum/thread-6661-post-41821.html#pid41821
