### ISSUE TITLE
No long options --active_beacon & --enable_status in hcxdumptool 6.3.1

### ISSUE THREAD

**Issue by piggy2011** [ZerBea/hcxdumptool#329]
I have installed the latest hcxdumptool 6.3.1 successfully on WSL2 Kali Linux and the wireless adapter(rtl88XXau) is also installed. Now, I'd like to run the command "hcxdumptool hcxdumptool -i wlan0 -o dumpfile.pcapng --active_beacon --enable_status=15" but it seems that neither --active_beacon nor --enable_status is provided in  hcxdumptool 6.3.1.  Would you pls help suggest what the command should be used in this hcxdumptool version? Thanks a lot!

**Comment by ZerBea** [comment]
active beacon is replaced by:
```
--beacontx=<digit>             : transmit BEACON of first n entries of ESSID list
                                  default: 10
```

status is enabled by default and can be sorted by --rds=1

usually this command line is enough:
`$ hcxdumptool -i wlan0 -o dumpfile.pcapng --rds=1`

If you need more than 10 ESSIDs to be beaconed, add becaontx:
`$ hcxdumptool -i wlan0 -o dumpfile.pcapng --becaontx=20 --rds=1`

**Comment by piggy2011** [comment]
> active beacon is replaced by:
> 
> ```
> --beacontx=<digit>             : transmit BEACON of first n entries of ESSID list
>                                   default: 10
> ```
> 
> status is enabled by default and can be sorted by --rds=1
> 
> usually this command line is enough: `$ hcxdumptool -i wlan0 -o dumpfile.pcapng --rds=1`
> 
> If you need more than 10 ESSIDs to be beaconed, add becaontx: `$ hcxdumptool -i wlan0 -o dumpfile.pcapng --becaontx=20 --rds=1`

Hi Zerbea, thanks a lot for your reply.  -o is replaced by -w according to hcxdumptool 6.3.1 help. Thanks!

**Comment by ZerBea** [comment]
Correct, thanks - nasty copy and paste error (-o -> -w).
