### ISSUE TITLE
issue install

### ISSUE THREAD

**Issue by godzillaplasma** [ZerBea/hcxdumptool#341]
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/rtl8812au-legacy-dkms.0.crash'
Error! Bad return status for module build on kernel: 6.2.0-31-generic (x86_64)
Consult /var/lib/dkms/rtl8812au-legacy/4.2.2~ppa/build/make.log for more information.
dpkg: error processing package rtl8812au-legacy-dkms (--configure):
 installed rtl8812au-legacy-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 rtl8812au-legacy-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ZerBea** [comment]
You're in the wrong place. This is a driver problem and it should be reported here:
https://github.com/aircrack-ng/rtl8812au/issues

Closed because it is not related to hcxdumptool.
