### ISSUE TITLE
hcxdumptool: unrecognized option 'enable_status=15'

### ISSUE THREAD

**Issue by khalidtabit** [ZerBea/hcxdumptool#402]
I try to run the attack with hcxdumptool but I get this error
![Uploading IMG_9997.JPG…]()

help please

**Comment by Jake-Grafton** [comment]
The option "enable_status=" has been deprecated due to the introduction of the real time display. Please run **hcxdumptool -h** for more options regarding the tool.

**Comment by ZerBea** [comment]
This is a rolling release and form always follows function.
Changes are mentioned in changelog. FAQ are answered in discussions and -h or --help always print some examples.
Closed, because it is not an issue.
