### ISSUE TITLE
Add a gpiowait.svg alongside gpiowait.odg

### ISSUE THREAD

**Issue by vertexgamer** [ZerBea/hcxdumptool#413]
I would like to propose the suggestion of converting gpiowait.odg to svg or pdf and adding it alongside the original, as they are a widely recognized vector format.
Otherwise it would be useful adding a note in readme.md pointing towards .odg being a vector file format

**Comment by ZerBea** [comment]
The format odg is very common on Linux and several tools can open or convert it:
LibrOffice Draw
MuPDF
ImageMagick (convert gpiowait.odg gpiowait.pdf or convert gpiowait.odg gpiowait.jpg or convert gpiowait.odg gpiowait.png)

I'll add a note to README.md

**Comment by ZerBea** [comment]
Done by this commit:
https://github.com/ZerBea/hcxdumptool/commit/21f7eaaf03fd6e7bedd66d2e3192b0c270755397
