### ISSUE TITLE
git release tag for 5.1.1 missing

### ISSUE THREAD

**Issue by anthraxx** [ZerBea/hcxdumptool#43]
it looks 5.1.1 was released but the git tag was not pushed?
At least so far once the version.h was bumped it was always at the same time as a release tag.

cheers

**Comment by ZerBea** [comment]
Thanks. It seems to be a race condition in my "push script".
 * [new tag]         5.1.1 -> 5.1.1
Should be working, now.

**Comment by anthraxx** [comment]
Its there, thanks a lot!

**Comment by ZerBea** [comment]
You're welcome. It's really great to see hcxtools in Arch Linux.

**Comment by anthraxx** [comment]
Glad to hear and happy to package :cat:
