### ISSUE TITLE
How can I delete this tool? 

### ISSUE THREAD

**Issue by Aggelos11** [ZerBea/hcxdumptool#438]
I want to delete it and download an older version of it? How do I do it? How can I also delete all of the packets and files that were automatically downloaded and created when I downloaded from GitHub??

**Comment by Jake-Grafton** [comment]
You can remove the tool using the **make** command in conjunction with options provided via the Makefile. To do so, change your current working directory to the hcxdumptool source directory via the **cd** command. `cd hcxdumptool` From here, elevate your privilege to super user levels via the **su** command. `su root` **Note:** Here, you'll need to provide your sudo password. After that has been done, run the **make** command with the options clean and uninstall. `make clean && make uninstall` Finally, remove the leftover files with the **rm** command. `cd .. && rm -rf hcxdumptool` Just like that, the tool and associated files have been removed from your system.

**Comment by ZerBea** [comment]
Closed because it has been answered above.
