### ISSUE TITLE
No man page to hcxdumptool

### ISSUE THREAD

**Issue by kretcheu** [ZerBea/hcxdumptool#50]
Hi,

I made a man page using output of 'hcxdumptool --help' putting in txt file and using script to convert to troff file.

Thanks 
Regards
kretcheu
:x

[hcxdumptool.txt](https://github.com/ZerBea/hcxdumptool/files/2972775/hcxdumptool.txt)

[genallman.sh.txt](https://github.com/ZerBea/hcxdumptool/files/2972793/genallman.sh.txt)

**Comment by ZerBea** [comment]
done with commit (a little bit more improved than the automatic generated one):
https://github.com/ZerBea/hcxdumptool/commit/7495f6721d650cc890a4031aa4a62ce73f50d8d3
