### ISSUE TITLE
issue with make error

### ISSUE THREAD

**Issue by arafat0951** [ZerBea/hcxdumptool#61]
# make

fails

**Comment by ZerBea** [comment]
Please attach error message.

make fails is really not enough!

**Comment by ZerBea** [comment]
BTW:
By latest commit:
https://github.com/ZerBea/hcxdumptool/commit/d002cdd023ea2ddf756c81c9efd8a626a9e59798
I added an error message to Makefile, if somebody tries to compile hcxdumptool on non Linux systems. This systems doesn't allow monitor mode and packet injection. Most if this systems are ‎proprietary. I don't support ‎proprietary systems.

**Comment by ZerBea** [comment]
closed due to missing error messages.
