### ISSUE TITLE
usleep deprecated

### ISSUE THREAD

**Issue by neheb** [ZerBea/hcxdumptool#65]
Some libc implementations like uClibc-ng optionally don't include deprecated functions.

usleep is one of them. It was removed from POSIX 2008 and replaced by nanosleep.

**Comment by ZerBea** [comment]
Just read man nanosleep() and it looks like a good idea tom move from usleep() to nanosleep().
Done by commit:
https://github.com/ZerBea/hcxdumptool/commit/889dab2da85268bf9012746a910770c6708acc9f
Please test and close issue, if it works, running OpenWRT.

**Comment by neheb** [comment]
Compiles.

**Comment by ZerBea** [comment]
Great. Nice improvement. Thanks.
