### ISSUE TITLE
Filter file usage causes segmentation fault

### ISSUE THREAD

**Issue by sjug** [ZerBea/hcxdumptool#7]
Hey there,

I see that you fixed a segfault bug recently but I'm running off master and I still have them.

`./hcxdumptool -c 1 -o cap.pcapng -i <interface> --filterlist=filter.file --filtermode=<1 or 2>`

filter.file:
```
112233445566 + comment
```

**Comment by ZerBea** [comment]
Fixed with latest commit.
We tried to use the filterlist entries for broadcast proberequests. Since we didn't received anything here, we run into a seg fault.
Please test and close when everyting's fine.

**Comment by sjug** [comment]
Thank you @ZerBea, working as expected now.
