### ISSUE TITLE
Confirmed PAU5 works

### ISSUE THREAD

**Issue by ukscone** [ZerBea/hcxdumptool#98]
I was going through my collection of wifi dongles and thought i'd give a PAU05 a try.
--do_rcascan & --check_driver both pass the dongle and a short 5 minute run and it grabbed some PMKID & MP so it seems to be ok.

Bus 001 Device 008: ID 148f:5372 Ralink Technology, Corp. RT5372 Wireless Adapter

root@kali:~/hcxdumptool# ./hcxdumptool -i wlan2 --check_driver
initialization...
starting driver test...
warning: NetworkManager is running with pid 378
 (service possbile interfering hcxdumptool)
warning: wpa_supplicant is running with pid 508
 (service possbile interfering hcxdumptool)
driver tests passed...
all required ioctl() system calls are supported by driver

terminating...
root@kali:~/hcxdumptool#

**Comment by ZerBea** [comment]
Great, thanks for the feedback:
As of today, MediaTek and RALINK chipsets working out of the box (driver included in Linux kernel).

Capturing WiFi traffic and performing high speed attacks depend highly on the capabilities of the driver!
- full monitor mode (receive all frames)
- full packet injection (transmit all frames)
- ioctl() system call support
and the receiver sensitivity as well as using a good antenna.
