### ISSUE TITLE
Unable to run in the OSX

### ISSUE THREAD

**Issue by springfred** [ZerBea/hcxdumptool#99]
OS not supported

**Comment by ZerBea** [comment]
From README.md:
Operating system: Arch Linux (strict), Kernel >= 4.19 (strict). It may work on other Linux systems (notebooks, desktops) and distributions, too (no support for other distributions, no support for other operating systems)

I am tired to wrestle against proprietary (closed source), commercial operating systems.

**Comment by ZerBea** [comment]
The driver must support monitor mode an full packet injection:
https://github.com/ZerBea/hcxdumptool/issues/98#issuecomment-589551355
That isn't the case on proprietary operating systems.

If you need that feature, you should request it here:
https://support.apple.com/en-ca
